# Generated by Django 2.2.5 on 2019-10-31 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unikey', models.CharField(default='', max_length=8)),
                ('google_calendar_email', models.CharField(default='', max_length=100)),
                ('ics', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Stickynote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, default='150', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, default='150', max_digits=5)),
                ('top', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('left', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('content', models.CharField(default='', max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetasker.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(default='', max_length=100)),
                ('acceptance', models.BooleanField(default=False)),
                ('invite_from_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetasker.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Friendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetasker.Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetasker.Student')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(default='', max_length=260)),
                ('share_state', models.BooleanField(default=False)),
                ('student', models.ManyToManyField(to='timetasker.Student')),
            ],
        ),
    ]
